add icons to button , update all icons name  and restyle all button
GSG-CF05/Food-Delivery-team-6 pull request #19
Opened 2022-03-19 10:09 UTC by nadershakshak

relate #18
add icons to button , update all icons name  and restyle all button
![image](https://user-images.githubusercontent.com/64221231/159116862-58517db2-abcd-47f6-897d-915a5afa9525.png)

2022-03-19 19:42 UTC, mostafayounis01 submitted a review, later dismissed

2022-03-19 20:03 UTC, MarwaKHTanani approved these changes, later dismissed

2022-03-20 07:04 UTC, husamkamal approved these changes

2022-03-20 07:11 UTC, husamkamal requested changes
add dot  to img url

2022-03-20 07:42 UTC, MohammedOmar123 approved these changes

2022-03-20 08:04 UTC, MarwaKHTanani approved these changes

2022-03-20 08:13 UTC, husamkamal approved these changes

2022-03-20 08:13 UTC, mostafayounis01 approved these changes

2022-03-20 08:13 UTC, merged