Update readme file
GSG-CF05/Food-Delivery-team-6 pull request #33
Opened 2022-03-21 11:04 UTC by mostafayounis01

2022-03-21 11:59 UTC, husamkamal requested changes
I am not the author of the api documentation and github page and there is a lack of user-journy

2022-03-24 14:08 UTC, MohammedOmar123 approved these changes

2022-03-24 14:08 UTC, nadershakshak approved these changes

2022-03-24 14:11 UTC, MarwaKHTanani approved these changes

2022-03-24 14:54 UTC, husamkamal approved these changes

2022-03-24 14:54 UTC, merged